### ISSUE TITLE
Missing `typescriptreact` parser

### ISSUE THREAD

**Issue by samueljoli** [nix-community/tree-sitter-nix#111]
Currently getting the following error:

`Error executing vim.schedule lua callback: ...rapped-nightly/share/nvim/runtime/lua/vim/treesitter.lua:425: Parser could not be created for buffer 11 and language "typescriptreact"`

Currently using the nightly install of vim:
```nix
    neovim-nightly-overlay = {
      url = "github:nix-community/neovim-nightly-overlay/f35afbe60a4ff71fd65fec3839fc38943f961951";
    };
```

Looking at the installed parsers and I don't see it listed.

**Comment by Atemu** [comment]
This does not look related to the nix parser at all?

**Comment by samueljoli** [comment]
@Atemu I was under the assumption that `nvim-treesitter.withAllGrammars` installs all parsers, for which I would have thought that `typescriptreact` would have been included. Sorry I'm new to nix and so I could be making false assumptions here. Do you have any idea what the issue might be?

**Comment by samueljoli** [comment]
@Atemu Ah you're right and apologies this is a mistake. This was fixed upstream [here](https://github.com/nvim-treesitter/nvim-treesitter/commit/707e352df6d737e545e1a7204f7395ba82e6d2d3). Closing this issue.
