### ISSUE TITLE
Release tree-sitter-nix on Crates.io

### ISSUE THREAD

**Issue by benwis** [nix-community/tree-sitter-nix#36]
Hi, I'd love to include tree-sitter-nix in my markdown to html converter crate, but to do that I can't have git dependencies.

Do you have any interest or plans on releasing the Rust adapter on crates.io?

**Comment by cstrahan** [comment]
Oh yeah, that's a good idea! I'll see if I can push it up tonight or this weekend.

**Comment by cstrahan** [comment]
@benwis I just now published the crate: https://crates.io/crates/tree-sitter-nix :tada: 

Lemme know if there's anything else I can do!
