### ISSUE TITLE
Parsing error with `post` keys

### ISSUE THREAD

**Issue by yrd** [nix-community/tree-sitter-nix#39]
I'm not quite sure if I'm missing something here, but I think I found a parsing error. This seems to be a minimal working example:

```nix
{
  post.postA = ''
  '';
}
```

When opening this in Helix, I get this error:

```
helix_view::document [ERROR] TS parser failed, disabeling TS for the current buffer: Err(InvalidRanges)
```

It seems to happen when `postFoo.postBar` is the key of an attribute set. I found it while trying to do this:

```nix
{
  systemd.services.postgresql.postStart = ''
  '';
}
```

I'm not entirely sure what's going on here. Feel free to close if this doesn't actually have anything to do with this parser.

**Comment by gabydd** [comment]
this is a problem on the helix side see https://github.com/helix-editor/helix/issues/3816
