### ISSUE TITLE
Bug: edge case slow highlighting performance

### ISSUE THREAD

**Issue by thenbe** [nix-community/tree-sitter-nix#46]
The following two files are exactly the same except for a single character. Despite that, opening `good.nix` is 6+ times faster than opening `repro.nix`.

```
$ hyperfine -N --ignore-failure "nvim good.nix -c exit" "nvim repro.nix -c exit"
Benchmark 1: nvim good.nix -c exit
  Time (mean ± σ):     174.9 ms ±   5.4 ms    [User: 138.0 ms, System: 44.0 ms]
  Range (min … max):   167.8 ms … 185.5 ms    16 runs

Benchmark 2: nvim repro.nix -c exit
  Time (mean ± σ):      1.192 s ±  0.110 s    [User: 0.506 s, System: 0.687 s]
  Range (min … max):    1.006 s …  1.321 s    10 runs

Summary
  nvim good.nix -c exit ran
    6.81 ± 0.66 times faster than nvim repro.nix -c exit
```

## Minimal repro

1. Create file `good.nix`:

   ```
   myFunc {
     preCheck = "hello";
     disabledTests = [
       # Lllllll aaaaaaa aaaa aaa `bar`
       ""
     ];
   }
   ```

1. Create file `repro.nix` (identical to first file except for one character)

   ```
   myFunc {
     preCheck = "hello";
     disabledTests = [
       # Lllllll aaaaaaa aaaa aaa `bar`
       "f"
     ];
   }
   ```

1. Observe that opening `repro.nix` is very slow, especially when compared to opening `good.nix`

## Version

```
NVIM v0.10.0-dev-3a34743
Build type: Release
LuaJIT 2.1.1693350652
```

nvim-treesitter: bf982eb

**Comment by asymmetric** [comment]
@thenbe I cannot reproduce. Note that it's better to run `nvim --clean`, so your personal config is not biasing the tests.

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `nvim --clean good.nix -c exit` | 109.3 ± 6.1 | 104.5 | 127.5 | 1.02 ± 0.06 |
| `nvim --clean repro.nix -c exit` | 107.0 ± 2.7 | 104.2 | 114.9 | 1.00 |

**Comment by thenbe** [comment]
I'll close this ticket as I can no longer reproduce this either.
