### ISSUE TITLE
Why are the queries not in sync with nvim-treesitter's queries?

### ISSUE THREAD

**Issue by viperML** [nix-community/tree-sitter-nix#75]
In my journey of investigating how tree-sitter works, I've noticed that the queries are duplicated here and at nvim-tresitter repo, and I see that they are not kept in sync.

- https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries/nix
- https://github.com/nix-community/tree-sitter-nix/tree/master/queries

What is that? Should neovim and other highlight program prefer any of the 2?

**Comment by leo60228** [comment]
The `highlights.scm` captures are [poorly specified](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#highlights) by upstream tree-sitter, so most editor plugins do not use parser-provided queries ([nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries), [Helix](https://github.com/helix-editor/helix/tree/master/runtime/queries), [emacs-tree-sitter](https://github.com/emacs-tree-sitter/tree-sitter-langs/tree/master/queries), [Zed](https://zed.dev/docs/extensions/languages#tree-sitter-queries)).

There has been some discussion about fixing this, which appears to mostly be in this nvim-treesitter issue: https://github.com/nvim-treesitter/nvim-treesitter/issues/3944
